import type { RailHistoryEntry, RailTableSnapshot } from "./model";
import type { PredictionSnapshot } from "@/lib/types";

export const FAKE_PREDICTIONS: PredictionSnapshot = {
  enabled: true,
  bettingReady: false,
  cluster: "devnet",
  minStakeLamports: 1_000_000,
  maxStakeLamports: 100_000_000,
  feeBps: 500,
  recentActivity: [],
  markets: [
    {
      id: "demo-action",
      kind: "next_action",
      question: "What will Vega do next?",
      status: "open",
      handNumber: 6,
      createdAt: Date.now(),
      totalPoolLamports: 42_000_000,
      outcomes: [
        { id: "fold", label: "Fold", poolLamports: 8_000_000 },
        { id: "passive", label: "Check / call", poolLamports: 13_000_000 },
        { id: "aggressive", label: "Bet / raise", poolLamports: 21_000_000 },
      ],
    },
    {
      id: "demo-hand",
      kind: "hand_winner",
      question: "Who takes the most chips in hand 6?",
      status: "open",
      handNumber: 6,
      createdAt: Date.now(),
      totalPoolLamports: 75_000_000,
      outcomes: [
        { id: "maya", label: "Maya", playerId: "maya", poolLamports: 25_000_000 },
        { id: "vega", label: "Vega", playerId: "vega", poolLamports: 40_000_000 },
        { id: "theo", label: "Theo", playerId: "theo", poolLamports: 10_000_000 },
      ],
    },
  ],
};

export const FAKE_TABLE: RailTableSnapshot = {
  code: "4821",
  phase: "playing",
  handNumber: 6,
  handsPerMatch: 12,
  street: "turn",
  board: [
    { rank: "A", suit: "hearts" },
    { rank: "7", suit: "clubs" },
    { rank: "7", suit: "spades" },
    { rank: "J", suit: "diamonds" },
  ],
  pots: [
    { id: "main", label: "Main pot", amount: 164, eligiblePlayerIds: ["maya", "vega", "theo", "dutch"] },
    { id: "side-1", label: "Side pot", amount: 72, eligiblePlayerIds: ["maya", "vega", "dutch"] },
  ],
  currentPlayerId: "vega",
  turnSecondsRemaining: 13,
  seatCount: 6,
  tellVisibility: "rail",
  players: [
    {
      id: "maya",
      name: "Maya",
      kind: "human",
      seatIndex: 0,
      stack: 312,
      committed: 32,
      cards: [{ rank: "A", suit: "spades" }, { rank: "Q", suit: "spades" }],
      inHand: true,
      cardsVisible: true,
      folded: false,
      allIn: false,
      position: "UTG",
      equity: 9.4,
      bestHand: "Two Pair",
      lastAction: "Bet 32",
      tell: {
        read: true,
        faceLocked: true,
        arousal: 76,
        bluffLikelihood: 68,
        confidence: 91,
        trend: "rising",
        evidence: ["blink rate 1.8× baseline", "jaw tension up"],
        emotion: "tense",
      },
    },
    {
      id: "vega",
      name: "Vega",
      kind: "ai",
      persona: "The surgeon",
      seatIndex: 1,
      stack: 226,
      committed: 32,
      cards: [{ rank: "7", suit: "diamonds" }, { rank: "K", suit: "clubs" }],
      inHand: true,
      cardsVisible: true,
      folded: false,
      allIn: false,
      position: "HJ",
      equity: 83.1,
      bestHand: "Three of a Kind",
      lastAction: "Thinking",
      talk: "That blink came right on the bet, Maya.",
      aiRead: {
        equity: 83,
        mathAction: "Call",
        finalAction: "Raise",
        target: "Maya",
        reasoning: "Trips are strong multi-way. Maya's abrupt blink spike makes the turn bet look less credible.",
        tellsUsed: ["blink spike", "tension rising"],
      },
    },
    {
      id: "theo",
      name: "Theo",
      kind: "human",
      seatIndex: 2,
      stack: 0,
      committed: 18,
      cards: [{ rank: "J", suit: "clubs" }, { rank: "T", suit: "clubs" }],
      inHand: true,
      cardsVisible: true,
      folded: false,
      allIn: true,
      position: "CO",
      equity: 6.2,
      bestHand: "Two Pair",
      lastAction: "All-in 18",
      tell: {
        read: true,
        faceLocked: true,
        arousal: 42,
        bluffLikelihood: 29,
        confidence: 84,
        trend: "falling",
        evidence: ["glanced at chips after the turn", "movement relaxed"],
        emotion: "focused",
      },
    },
    {
      id: "dutch",
      name: "Dutch",
      kind: "ai",
      persona: "The grinder",
      seatIndex: 3,
      stack: 178,
      committed: 32,
      cards: [{ rank: "K", suit: "hearts" }, { rank: "Q", suit: "diamonds" }],
      inHand: true,
      cardsVisible: true,
      folded: false,
      allIn: false,
      position: "BTN",
      equity: 1.3,
      bestHand: "Pair",
      isButton: true,
      lastAction: "Call 32",
      aiRead: {
        equity: 18,
        mathAction: "Fold",
        finalAction: "Call",
        target: "Maya",
        reasoning: "The price is thin, but Maya's hesitation and falling composure widen her betting range.",
        tellsUsed: ["slow decision", "composure falling"],
      },
    },
    {
      id: "rhea",
      name: "Rhea",
      kind: "human",
      seatIndex: 4,
      stack: 401,
      committed: 0,
      cards: [{ rank: "5", suit: "hearts" }, { rank: "5", suit: "diamonds" }],
      inHand: true,
      cardsVisible: true,
      folded: true,
      allIn: false,
      position: "SB",
      equity: 0,
      bestHand: "Two Pair",
      isSmallBlind: true,
      lastAction: "Fold",
      tell: {
        read: true,
        faceLocked: true,
        arousal: 24,
        bluffLikelihood: 47,
        confidence: 88,
        trend: "stable",
        evidence: ["no significant deviation"],
        emotion: "neutral",
      },
    },
    {
      id: "omar",
      name: "Omar",
      kind: "human",
      seatIndex: 5,
      stack: 263,
      committed: 0,
      cards: [{ rank: "9", suit: "diamonds" }, { rank: "4", suit: "spades" }],
      inHand: true,
      cardsVisible: true,
      folded: true,
      allIn: false,
      position: "BB",
      equity: 0,
      bestHand: "Pair",
      isBigBlind: true,
      lastAction: "Fold",
      // Camera on, no bet yet: the rail shows raw signals until the first read.
      tell: {
        read: false,
        faceLocked: true,
        blinkRate: 17,
        tension: 22,
        evidence: [],
        emotion: "uncertain",
      },
    },
  ],
};

export const FAKE_HISTORY: RailHistoryEntry[] = [
  { id: "h1", handNumber: 6, street: "preflop", message: "Maya opened to 8", playerName: "Maya", tone: "action" },
  { id: "h2", handNumber: 6, street: "preflop", message: "Theo called 8", playerName: "Theo", tone: "action" },
  { id: "h3", handNumber: 6, street: "preflop", message: "Vega raised to 18", playerName: "Vega", isAi: true, tone: "action" },
  { id: "h4", handNumber: 6, street: "flop", message: "Flop dealt: A♥ 7♣ 7♠", tone: "deal" },
  { id: "h5", handNumber: 6, street: "flop", message: "Theo moved all-in for 18", playerName: "Theo", tone: "action" },
  { id: "h6", handNumber: 6, street: "turn", message: "Turn dealt: J♦", tone: "deal" },
  { id: "h7", handNumber: 6, street: "turn", message: "Maya bet 32", playerName: "Maya", tone: "action" },
];

export function tableForCode(code: string): RailTableSnapshot {
  return { ...FAKE_TABLE, code, players: FAKE_TABLE.players.map((player) => ({ ...player })) };
}
